# Generated by Django 4.2.29 on 2026-04-18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree_program", models.CharField(max_length=255)),
                ("semester", models.PositiveSmallIntegerField()),
                (
                    "cgpa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("skills_interests", models.TextField(blank=True, default="[]")),
                (
                    "preferred_opportunity_types",
                    models.TextField(blank=True, default="[]"),
                ),
                ("financial_need", models.CharField(max_length=100)),
                ("location_preference", models.CharField(max_length=255)),
                ("past_experience", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
