# Generated by Django 4.2.29 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_studentemailbatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentemailbatch",
            name="total_recipients",
            field=models.PositiveIntegerField(),
        ),
    ]
