# Generated by Django 4.2.29 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_studentemailbatch_total_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentemailbatch",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="studentemailbatch",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="StudentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="emails",
                        to="api.studentemailbatch",
                    ),
                ),
            ],
        ),
    ]
