# Generated by Django 4.2.29 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_studentemail_and_optional_batch_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentemail",
            name="rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentemail",
            name="recommendation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
